site_name: Terraveil Journal
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      primary: red
      accent: orange
nav:
  - Home: index.md
  - Characters:
    - Silas Corvin: characters/silas/index.md
  - Campaigns:
    - Campaign: campaigns/index.md
    - Session 1: campaigns/Session-1.md
    #- Session 2: campaigns/Session-2.md
  - Locations:
    - Coming Soon: locations/index.md
  - NPCs:
    - Coming Soon: npcs/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - toc:
      permalink: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js
  - https://cdn.jsdelivr.net/npm/@fullcalendar/google-calendar@6.1.8/index.global.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css
  - assets/custom.css