site_name: Silas Corvin
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      primary: red
      accent: orange
nav:
  - Home: index.md
  - Campaigns: 
    - Session 1: campaigns/Session 1.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
