site_name: Terraveil Journal
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      primary: red
      accent: orange
nav:
  - Home: index.md
  - Characters:
    - Silas Corvin: characters/silas/index.md
  - Campaigns: 
    - Session 1: campaigns/Session-1.md
    - Session 2: campaigns/Session-2-Test.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
extra_css:
  - assets/custom.css
