name: deploy

on:
  push:
    branches: [ "main" ]   # build on every push to main

permissions:
  contents: write          # needed to push the built site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build and deploy
        run: mkdocs gh-deploy --force
